config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users

  # ресурс сессий (только три экшена :new, :create, :destroy)
  resources :sessions, only: [:new, :create, :destroy]

  # ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  #  синонимы путей - в дополнение к созданным в ресурсах выше
  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
  get 'delete_account' => 'users#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  ##Relations
  belongs_to :user
  belongs_to :questioning_user, class_name: 'User', optional: true

  ##Validates
  validates :text, :user, presence: true
  validates_length_of :text, maximum: 255
  ## Callbacks

  ##Etc.

end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord

  attr_accessor :password

  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new
  ##Relations
  has_many :questions

  ##Validates
  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :password, presence: true, on: :create
  validates_confirmation_of :password
  validates_format_of :email, with: /@/
  validates_format_of :username, with: /\A[a-zA-Z0-9_]+\z/
  validates_length_of :username, maximum: 40

  ##Callbacks
  before_save :encrypt_password
  before_validation { self.username.downcase! }

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # метод-помощник, доступный во вьюхах
  helper_method :current_user

  private

  # хелпер, достающий текущего юзера по данным аутентификации в сессии
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # редиректит юзера на главную с предупреждением
  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # инициализируем объект вопрос для экшенов кроме :edit, :update, :destroy
  before_action :load_question, only: [:edit, :update, :destroy]

  # проверяем имеет ли юзер доступ к экшену
  before_action :authorize_user, except: [:create]

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.questioning_user = current_user if current_user.present?

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private

  # загружаем вопрос
  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end


  def question_params
    # защита от уязвимости -- пользователь может менять ответы только у собственных вопросов
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # создает в объекте session новый факт залогиненности пользователя
  # если он правильно сообщил мэйл/пароль
  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new
    end
  end

  # удаляет сессию залогиненного юзера
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились! Приходите еще!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:index, :create, :new]

  # проверяем имеет ли юзер доступ к экшену
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь успешно зарегестрирован!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Аккаунт успешно удален!!'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  private

  # если загруженный из базы юзер и текущий залогиненный не совпадают - посылаем его
  def authorize_user
    reject_user unless @user == current_user
  end

  # загружаем из базы запрошенного юзера
  def load_user
    @user ||= User.find params[:id]
  end

  # явно задаем список разрешенных параметров для модели user
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :background_color)
  end
end

def background_color
  if @user.nil?
    @background_color = "#005a55"
  else
    @background_color = @user.background_color
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'cookie.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def background_color
    @background_color = @user.background_color if @user.present?
  end

  def count_questions
    I18n.t('question', count: @questions.count)
  end

  def sklonenie(number, krokodil, krokodila, krokodilov)
    ostatok_10 = number % 10
    ostatok_100 = number % 100

    return krokodilov if (11..14).include?(ostatok_100)

    case ostatok_10
      when 1
        krokodil
      when (2..4)
        krokodila
      else
        krokodilov
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def link_to_user_profile
    link_to current_user.username, user_path(current_user)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <%#Именно здесь мы подключаем все стили и прописываем один (в рамках обучения)%>
  <%#тег title для всех страниц сайта%>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <style>
    .user-header {
      background-color: <%= background_color%>;
    }
  </style>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <div class="header-logo">
      <%#Ссылка на главную страницу сайта root_path%>
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>
    
    <div class="header-nav">
      <!-- Если есть текущий юзер (значит он залогинен) -->
      <% if current_user %>
        <!-- Даем ссылки на его профиль и на логаут -->
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', log_out_path %>
      <% else %>
        <!-- Если нету - ссылки на регистрацию и логин -->
        <%= link_to 'Зарегистрироваться', sign_up_path, class: 'button button-light button-small' %>
        <%= link_to 'Войти', log_in_path, class: 'button button-light button-small' %>
      <% end %>
    
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<!-- Форма для создания/правки вопроса -->

<div class="form">
  <!-- Форма для объекта @question -->
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <!-- Скрытое поле - айдишник юзера, кому задается вопрос -->
    <%= f.hidden_field :user_id %>
    
    <div class="form-field">
      <%= f.label :text, "Вопрос:", class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>
    
    
    <!-- Простая авторизация - может ли текущий юзер править вопрос? -->
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>
    
    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<!-- Локальная переменная этого паршиала -->
<% question ||= nil %>
<!-- Определяем какая будет иконка -->
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>


<div class="question">
  <div class="question-content">
    <% if question.questioning_user.present? %>
      Вопрос от пользователя: <%= link_to "@#{question.questioning_user.username}",
                                          user_path(question.questioning_user) %>
    <% else %>
      Вопрос от анонима:
    <% end %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>
    
    <!-- Если вопрос имеет ответ, показать его -->
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>
    
    <div class="question-date">
      <!-- Локализованный вывод даты вопроса в коротком формате -->
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>
  
  <!-- Простая авторизация: только владелец вопроса может его редактировать -->
  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: { confirm: 'Точно удалить вопрос?' } %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<!-- Страница редактирования вопроса -->
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>
  
  <div class="column-1-2">
    <!-- Подключаем паршиал form -->
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<!-- Страница редактирования пользователя -->

<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>
  
  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <!-- Вывод ошибок валидации пользователя (если есть) -->
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>
      
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>
      
      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>
      
      <div class="form-field">
        <%= label_tag(:background_color, 'Цвет фона') %>
        <%= color_field(:user, :background_color, class: 'form-color-field') %>
      </div>
      
      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>
      
      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>
      
      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>
      
      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>
    <div class="form-action buffer-top">
      <%= link_to 'Удалить аккаунт', user_path(@user),
        method: :delete, data: { confirm: 'Точно удалить аккаунт?' }, class: 'button button-red button-small' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>
  
  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%# Пользуемся аж тремя хелперами %>
        <%# link_to — генерирует ссылку %>
        <%# image_tag — генерирует картинку %>
        <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
        <%# Хелпер user_path(user) возвращает относительный путь %>
        <%# страницы пользователя, например /users/1 %>
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
      <%= user.username %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>
  
  <div class="column-1-2">
    <div class="form">
      <%= form_for @user do |f| %>
        
        <!-- Вывод ошибок валидации пользователя (если есть) -->
        <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="form-field">
          <%= f.label :email, 'Логин (email)', class: 'form-label' %>
          <%= f.text_field :email, class: 'form-text-field' %>
        </div>
        
        <div class="form-field">
          <%= f.label :username, 'Никнейм', class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>
        
        <div class="form-field">
          <%= f.label :name, 'Имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>
        
        <div class="form-field">
          <%= f.label :password, 'Пароль', class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>
        
        <div class="form-field">
          <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>
        
        <div class="form-action">
          <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>
  
  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>
  
  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>
  
  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
  
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
  
  
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <% quantity = @questions_count %>
      <h1 class="title-small"><%= quantity %></h1>
      <p><%= "#{count_questions}" %></p>
    </div>
    <div class="column-1-3">
      <% quantity = @answers_count %>
      <h1 class="title-small"><%= quantity %></h1>
      <p><%= sklonenie(quantity, 'ответ', 'ответа', 'ответов') %></p>
    </div>
    <div class="column-1-3">
      <% quantity = @unanswered_count %>
      <h1 class="title-small"><%= quantity %></h1>
      <p><%= sklonenie(quantity, 'безответный', 'безответных', 'безответных') %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%#Мы используем хелпер form_for, принимающий на вход блок erb-кода, в котором доступна%>
      <%#переменная f, содержащая так называемый form builder, с помощью которого можно делать%>
      <%#поля формы для нового вопроса%>
      <%= form_for @new_question do |f| %>
        <%#С помощью объекта для создания полей формы, связанной с моделью @new_question%>
        <%#Мы создаем инпуты с нужными полями для формы, значения будут подставлены rails%>
        <%#автоматически%>
        <%= f.hidden_field :user_id %>
        
        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>
        
        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%#Блок со списком вопросов к пользователю%>
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="user-question-form">
      <%= "Всего: #{@questions.count} #{count_questions}" %>
    </div>
    <div class="questions-list">
      <%#Обратите внимание, как мы делаем цикл по всем вопросам,%>
      <%#точно также, как мы делали циклы в ruby%>
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>